import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import ClientSideProvider from "./ClientSideProvider";

const myFont = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Clipcraft AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={myFont.className} cz-shortcut-listen="true">
        <ClientSideProvider>{children}</ClientSideProvider>
      </body>
    </html>
  );
}
